ITI.Sauce/ITI.sauce.cs/Controllers/MemberShipController.cs
using ITI.Sauce.Models;
using ITI.Sauce.Repository;
using Microsoft.AspNetCore.Mvc;
using ITI.Sauce.ViewModels;


namespace ITI.sauce.MVC.Controllers
{
    public class MemberShipController : Controller
    {
        private readonly MemberShipRepository MemberShipeRepo;
        private readonly UnitOfWork UnitOfWork;
        public MemberShipController(MemberShipRepository _RepoMemberShip, UnitOfWork _unitOfWork)
        {
            //DBContext dBContext = new DBContext();
            this.MemberShipeRepo = _RepoMemberShip;
            UnitOfWork = _unitOfWork;
        }
        public IActionResult Get(int id = 0, float Price = 0, string TypeEn = "", string TypeAr = "", string orderby = "ID", bool isAscending = false, int pageIndex = 1,

                         int pageSize = 20)
        {
            var ResultData =
               MemberShipeRepo.Get(id, Price, TypeEn, TypeAr, orderby, isAscending, pageIndex, pageSize);
            return View(ResultData);
        }

        public IActionResult GetVendorMemperShip(int VendorId = 0)
        {
            return View();
        }
        public IActionResult Search(int pageIndex = 1, int pageSize = 2)
        {
            var Data = MemberShipeRepo.Search(pageIndex, pageSize);
            return View("Get", Data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(MemberShipEditViewModel model)
        {
            if (ModelState.IsValid == true)
            {
                MemberShipeRepo.Add(model);
                UnitOfWork.Save();
                return RedirectToAction("Search");
            }
            else
                return View();
        }





        [HttpGet]
        public IActionResult Update(int ID)
        {
            var Results = MemberShipeRepo.GetOne(ID);

            return View(Results.ToEditViewModel());

        }






        [HttpPost]
        public IActionResult Update(MemberShipEditViewModel model, int ID = 0)
        {
            MemberShipeRepo.Update(model);
            UnitOfWork.Save();
            return RedirectToAction("Get");

        }
    }

}

ITI.Sauce/ITI.sauce.cs/Views/MemberShip/Add.cshtml
@using ITI.Sauce.ViewModels
@model MemberShipEditViewModel


<!DOCTYPE html>
<html>
<head>
    @*<link rel="stylesheet" href="~/Content/CSS/VendorTable.css"/>*@
<meta name="viewport" content="width=device-width, initial-scale=1">
@section StyleSection {
    <link rel="stylesheet" href="~/Content/CSS/AddGeneralToDB.css" />
}
<style>
    
#btnAdd {
    width: 100%;
    background-color: #143444;
    color: #F6EE99;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    text-decoration:none;
    float:right;
}


</style>
</head>
<body>

  <div>
<form data-ajax="true"  asp-action="Add" asp-controller="MemberShip" method="post">
    <h1>Add to MemberShip Table</h1>
    <br />
    <p>Please Choose Your MemberShip.</p>
     <div asp-validation-summary="ModelOnly" style="color:red" ></div>
    <hr>

    <label asp-for="OrderNum"> Order Number </label>
    <input  asp-for="OrderNum">
    <span asp-validation-for="OrderNum" style="color:red"></span>



    <label asp-for="Price"> Price </label>
    <input  asp-for="Price">
    <span asp-validation-for="Price" style="color:red"></span>

    <label asp-for="TypeEn"> English Type </label>
    <input  asp-for="TypeEn">
    <span asp-validation-for="TypeEn" style="color:red"></span>

    <label asp-for="TypeAr"> Arabic Type </label>
    <input  asp-for="TypeAr">
    <span asp-validation-for="TypeAr" style="color:red"></span>


    <button id="btnAdd" type="Submit" value="MemberShip">Add</button>
</form>
  </div>

</body>
</html>

ITI.Sauce/ITI.sauce.cs/Views/MemberShip/Get.cshtml
@using ITI.Sauce.ViewModels



@model IPagedList<MemberShipViewModel>

	
@section StyleSection
{
<link rel="stylesheet" href="~/Content/CSS/MemberShip.css"/> 
<link rel="stylesheet" href="~/Content/CSS/GeneralTable.css"/>


}


<h2>MemberShip</h2>
    <a asp-action="Add" asp-controller="MemberShip" id="btnAdd">Add</a>

<table>
  <tr>
    <th>ID</th>
    <th>Price</th>
    <th>TypeEn</th>
    <th>TypeAr</th>
    <th>Update</th>

  </tr>
   
   @foreach (var M in Model)
  
{
	<tr>
	<td>@M.ID</td>
	<td>@M.Price</td>
	<td>@M.TypeEn</td>
	<td>@M.TypeAr</td>
    <td><a asp-action="Update" asp-controller="MemberShip" asp-route-ID="@M.ID">Update</a></td>
   </tr>
}
  
</table>
<div>
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Search", new { pageIndex = page }),
        new X.PagedList.Web.Common.PagedListRenderOptions
        {
        DisplayItemSliceAndTotal = true,
        ContainerDivClasses = new[] { "navigation" },
        LiElementClasses = new[] { "page-item" },
        PageClasses = new[] { "page-link" },
        })
    </div>
    <div>
    <script>
        $(document).ready(function() {
            $('ul.pagination > li.disabled > a').addClass('page-link');
        });
    </script>
</div>

ITI.Sauce/ITI.sauce.cs/Views/MemberShip/Update.cshtml
@using ITI.Sauce.ViewModels


@model MemberShipEditViewModel

<!DOCTYPE html>
<html>
<head>
    @*<link rel="stylesheet" href="~/Content/CSS/VendorTable.css"/>*@
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
    input[type=text],[type=email],[type=password], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}



div {
    border-radius: 5px;
    padding: 20px;

      
}
#btnAdd {
    width: 100%;
    background-color: #143444;
    color: #F6EE99;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    text-decoration:none;
    float:right;
}

#customFile{
    width: 22%;
    background-color: #143444;
    color: #F6EE99;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    text-decoration:none;
    float:left;
}

</style>
</head>
<body>

  <div>
<form data-ajax="true"  asp-action="Update" asp-controller="MemberShip" method="post">
    <h1>Update MemberShip</h1>
    
     <div asp-validation-summary="ModelOnly" style="color:red" ></div>
    <hr>

    <label asp-for="Price"> Price </label>
    <input  asp-for="Price">
    <span asp-validation-for="Price" style="color:red"></span>

    <br />

    <label asp-for="TypeEn"> English Type </label>
    <input  asp-for="TypeEn">
    <span asp-validation-for="TypeEn" style="color:red"></span>
    <br />


    <label asp-for="TypeEn"> English Type </label>
    <input  asp-for="TypeEn">
    <span asp-validation-for="TypeEn" style="color:red"></span>

    <br />
    <label asp-for="TypeAr"> Arabic Type </label>
    <input  asp-for="TypeAr">
    <span asp-validation-for="TypeAr" style="color:red"></span>

    
    <br />

    <button asp-action="Search" asp-controller="MemberShip" id="btnAdd" type="Update" value="MemberShip">Update MemberShip</button>
</form>
  </div>

</body>
</html>