ITI.Sauce/ITI.sauce.cs/Controllers/CategoryController.cs
using ITI.Sauce.Models;
using ITI.Sauce.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Abp.Linq.Expressions;
using Microsoft.AspNetCore.Mvc;
using ITI.Sauce.Repository;
using Microsoft.AspNetCore.Authorization;

namespace ITI.sauce.MVC.Controllers
{
    public class CategoryController : Controller
    {
        private readonly CategoryRepository CateRepo;
        private readonly UnitOfWork UnitOfWork;
        public CategoryController(CategoryRepository _cateRepo, UnitOfWork _unitOfWork)
        {
            CateRepo = _cateRepo;
            UnitOfWork = _unitOfWork;
        }

        //[Authorize(Roles = "User,Vendor")]

        public IActionResult Get (int ID =0 ,string orderBy = null, bool isAscending = false , string NameEN = "",
            string NameAR = "",int pageIndex = 1 , int pageSize = 20 )
        {
            var data =
                CateRepo.Get(ID, orderBy, isAscending, NameEN, NameAR, pageIndex, pageSize);
            return View(data);
        }
        public IActionResult Search(int pageIndex = 1, int pageSize = 4)
        {
            var Data = CateRepo.Search(pageIndex, pageSize);
            return View("Get", Data);
        }
        [HttpGet]
        public IActionResult Add ()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add (CategoryEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                CateRepo.Add(model);
                UnitOfWork.Save();
                return RedirectToAction("Get");
            }
            else
            {
                return View();
            }
           
        }





        [HttpGet]
        public IActionResult Update(int Id)
        {
            var Results = CateRepo.GetOne(Id);

            return View(Results.ToEditViewModel());

        }






        [HttpPost]
        public IActionResult Update(CategoryEditViewModel model, int ID = 0)
        {
            CateRepo.Update(model);
            UnitOfWork.Save();
            return RedirectToAction("Get");

        }






        [HttpGet]
        public IActionResult Remove(CategoryEditViewModel model, int ID)
        {
            var res = CateRepo.Remove(model);
            UnitOfWork.Save();
            return RedirectToAction("Get");


        }
    }
    
}

ITI.Sauce/ITI.sauce.cs/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using ITI.Sauce.Models;
using Microsoft.AspNetCore.Mvc;
using ITI.Sauce.Repository;
using ITI.Sauce.ViewModels;

namespace ITI.sauce.MVC.Controllers
{
    public class OrderController : Controller
    {
        OrderRepository ordRepo;
        private readonly UnitOfWork UnitOfWork;

        public OrderController(OrderRepository _ordRepo, UnitOfWork _unitOfWork)
        {
            //DBContext dBContext = new DBContext();
            ordRepo = _ordRepo;
            UnitOfWork = _unitOfWork;
        }
        public IActionResult Get(int ID = 0, string orderBy = null, bool isAscending = false, string UserId = "",
             DateTime? registerDate = null,int pageIndex = 1, int pageSize = 20)
                    
        {
            var data =
                ordRepo.Get(ID, orderBy,isAscending, UserId, registerDate, pageIndex, pageSize);
            return View(data);
        }

        public IActionResult GetById(int id)
        {
            var data =
           ordRepo.Get(id);
            return View(data);
        }

        //[Authorize(Roles = "Admin")]
        public IActionResult Search(int pageIndex = 1, int pageSize = 2)
        {
            var Data = ordRepo.Search(pageIndex, pageSize);
            return View("Get", Data);
        }

        // [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        //[Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Add(OrderEditViewModel model)
        {
            if (ModelState.IsValid == true)
            {
                ordRepo.Add(model);
                UnitOfWork.Save();
                return RedirectToAction("Search");
            }
            else
                return View();
        }


        [HttpGet]
        public IActionResult Update(int Id)
        {
            var Results = ordRepo.GetOne(Id);
            return View(Results.ToEditViewModel());
        }



        [HttpPost]
        public IActionResult Update(OrderEditViewModel model, int ID = 0)
        {

            ordRepo.Update(model);
            UnitOfWork.Save();
            return RedirectToAction("Search");

        }

        [HttpGet]
        public IActionResult Remove(OrderEditViewModel model, int ID)
        {
            var res = ordRepo.Remove(model);
            UnitOfWork.Save();
            return RedirectToAction("Search");


        }
    }
}

ITI.Sauce/ITI.sauce.cs/Controllers/RatingController.cs
using ITI.Sauce.Models;
using ITI.Sauce.Repository;
using ITI.Sauce.ViewModels;
using ITI.Sauce.ViewModels.Shared;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ITI.sauce.MVC.Controllers
{
    public class RatingController : Controller
    {
        private readonly UnitOfWork UnitOfWork;
        private readonly RatingRepository RatepRepo;
        private readonly UserRepository UserRepo;



        public RatingController( UnitOfWork _unitOfWork
            , RatingRepository _RatepRepo, UserRepository _UserRepo)
        {
            UnitOfWork = _unitOfWork;
            RatepRepo = _RatepRepo;
            UserRepo = _UserRepo;
        }
        public IActionResult Get(int id = 0, int RatingValue = 0,
                string orderyBy = "", bool isAscending = false,
                int pageIndex = 1, int pageSize = 20)
        {
            var data =
            RatepRepo.Get(id, RatingValue,null,orderyBy,
                isAscending, pageIndex, pageSize);
            return View(data);
        }
        public IActionResult GetById(int id)
        {
            var data =
           RatepRepo.Get(id);
            return View(data);
        }
        public IActionResult Search(int pageIndex = 1, int pageSize = 2)
        {
            var Data = RatepRepo.Search(pageIndex, pageSize);
            return View("Get", Data);
        }
        [HttpGet]
        public IActionResult Add()
        {
            IEnumerable<SelectListItem> Ratings =
                GetRatingNames(RatepRepo.GetRecipeID());
            ViewBag.Rating = Ratings;

           
            return View();
        }

        private IEnumerable<SelectListItem> GetRatingNames(List<TextValueViewModel> list)
        {
            return list.Select(i => new SelectListItem
            {
                Text = i.Text,
                Value = i.Value.ToString()
            });
        }

        

        [HttpPost]
        public IActionResult Add(RatingEditViewModel model)
        {
            if (ModelState.IsValid == true)
            {
                RatepRepo.Add(model);
                UnitOfWork.Save();
                return RedirectToAction("Search");
            }
            else
                return View();
        }






        [HttpGet]
        public IActionResult Update(int Id)
        {
            var Results = RatepRepo.GetOne(Id);

            return View(Results.ToEditViewModel());

        }






        [HttpPost]
        public IActionResult Update(RatingEditViewModel model, int ID = 0)
        {
            RatepRepo.Update(model);
            UnitOfWork.Save();
            return RedirectToAction("Get");

        }









    }
}

ITI.Sauce/ITI.sauce.cs/Controllers/RestaurantController.cs
using System.Security.Claims;
using ITI.Sauce.Models;
using ITI.Sauce.Repository;
using ITI.Sauce.ViewModels;
using ITI.Sauce.ViewModels.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ITI.sauce.MVC.Controllers
{
    public class RestaurantController : Controller
    {
        private readonly RestaurantRepository ResRepo;
        private readonly UnitOfWork UnitOfWork;
        public RestaurantController(RestaurantRepository _RepoRes, UnitOfWork _unitOfWork)
        {
            this.ResRepo = _RepoRes;
            UnitOfWork = _unitOfWork;
        }
        //[Authorize(Roles = "Admin,User,Vendor")]
        public IActionResult Get(string Vendor_ID = "", int id = 0, DateTime? FromTime = null, DateTime? ToTime = null,
            string NameEn = "", string NameAr = "", DateTime? registerDate = null,
            bool isDeleted = false, string orderby = "ID", bool isAscending = false,
            int pageIndex = 1, int pageSize = 20)
        {
            var Resultdata =
                ResRepo.Get(Vendor_ID, id, FromTime, ToTime, NameEn, NameAr, registerDate, isDeleted, orderby, isAscending, pageIndex, pageSize);
            return View("Get", Resultdata);
        }
        //[Authorize(Roles = "Admin,Vendor")]
        public IActionResult Search(int pageIndex = 1, int pageSize = 4)
        {

            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.Reataurant = ResRepo.GetList().Where(v => v.Vendor_ID == userId);
            var Data = ResRepo.Search(pageIndex, pageSize);
            return View("Get", Data);
        }
        [Authorize(Roles = "Vendor")]
        [HttpGet]
        public IActionResult Add()
        {
            var claimsIdentity = (System.Security.Claims.ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            return View(new RestaurantEditViewModel { Vendor_ID = userId });
        }
        private IEnumerable<SelectListItem> GetRestaurantNames(List<TextValueViewModel> list)
        {
            return list.Select(i => new SelectListItem
            {
                Text = i.Text,
                Value = i.Value.ToString()
            });
        }

        [Authorize(Roles = "Vendor")]
        [HttpPost]
        public IActionResult Add(RestaurantEditViewModel model)
        {
            //model.
            string? bookUploadUrl = "/Content/Uploads/Resturant/";

            string newFileName = Guid.NewGuid().ToString() + model.Image.FileName;
            model.ImageUrl = bookUploadUrl + newFileName;

            FileStream fs = new FileStream(Path.Combine
                (
                    Directory.GetCurrentDirectory(),
                    "Content",
                   "Uploads", "Resturant", newFileName
                ), FileMode.Create);

            model.Image.CopyTo(fs);
            fs.Position = 0;
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ResRepo.Add(model);
            UnitOfWork.Save();

            return RedirectToAction("Get", new { Vendor_ID = userId });
        }
        [HttpGet]
        public IActionResult Update(int Id)
        {
            IEnumerable<SelectListItem> Restaurants =
                GetRestaurantNames(ResRepo.GetCRestaurantDropDown());
            ViewBag.Restaurants = Restaurants;
            var Results = ResRepo.GetOne(Id);
            return View(Results.ToEditViewModel());
        }

        [HttpPost]
        public IActionResult Update(RestaurantEditViewModel model, int ID = 0)
        {
            ResRepo.Update(model);
            UnitOfWork.Save();
            return RedirectToAction("Get");
        }

        [HttpGet]
        public IActionResult Remove(RestaurantEditViewModel model, int ID)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var res = ResRepo.Remove(model);
            UnitOfWork.Save();

            //if (!this.User.HasClaim(c => c.Value == "Vendor"))
            //{
            //    return RedirectToAction("Get", new { Vendor_ID = userId });
            //}
            //else
            return RedirectToAction("Search");

        }
        public IActionResult AcceptRestaurant(RestaurantEditViewModel model, int ID)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ResRepo.AcceptRestaurant(model, ID);
            UnitOfWork.Save();
            return RedirectToAction("Search");
            

        }




    }
}

ITI.Sauce/ITI.sauce.cs/Views/Shared/_Layout.cshtml
@using ITI.Sauce.Models
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<Users> _SignInManager

   
     
@{
    var claimsIdentity = (System.Security.Claims.ClaimsIdentity)this.User.Identity;
    var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
    var userId = claim.Value;
}     

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin Dashboard</title>



    <link
      rel="stylesheet"
      href="~/Content/lib/font-awesome/css/all.css"
    />
    <link rel="stylesheet" href="~/Content/CSS/vendor.css" />
    
    @RenderSection("StyleSection",false)
</head>
<body>
    <aside id="side">
        <div class="close" id="close-btn" onclick="closeMenu()">
<i class="fas fa-solid fa-xmark" ></i>

        </div>
        <ul class="mysidebar">

            <li>
                <a asp-action="Index" asp-controller="Home" class="mylogo"><i class="fas fa-utensils"></i>Sauce</a>

            </li>
            
                @if (ViewBag.Flag == null)
                    ViewBag.Flag = false;
                @if ((!ViewBag.Flag && this.User.HasClaim(c => c.Value == "Vendor"))  )
                {
                    <!--View Recipes / Reviews / Orders-->
                    <li><a asp-action="Get" asp-controller="Restaurant" asp-route-Vendor_ID="@userId">View Restaurant </a></li>
                    <li><a asp-action="Get" asp-controller="Rating" asp-route-Vendor_ID="@userId">View Reviews </a></li>

                         <li><a asp-action="search" asp-controller="Ingredient">View Ingredients </a></li>
                        <li><a asp-action="Search" asp-controller="Category">View Category </a></li>
                @if (this.User.HasClaim(c => c.Value == "Vendor"))
                {
                    <li><a asp-action="GetOrders" asp-controller="Vendor" asp-route-Vendor_ID="@userId">View Orders </a></li>
                }
                else
                {
                    <li><a asp-action="Get" asp-controller="Order" asp-route-Vendor_ID="@userId">View Orders </a></li>
                }


            }

            
                    @if (this.User.HasClaim(c => c.Value == "Admin"))
                    {
                        <li><a asp-action="Search" asp-controller="Recipe" >View Recipes </a></li>
                    <li><a asp-action="Search" asp-controller="Rating" >View Reviews </a></li>
                    <li><a asp-action="Search" asp-controller="Order" >View Orders </a></li>
                        <li><a asp-action="Search" asp-controller="Users">View Users </a></li>
                        <li><a asp-action="search" asp-controller="Vendor">View Vendors </a></li>
                        <li><a asp-action="search" asp-controller="Ingredient">View Ingredients </a></li>
                        <li><a asp-action="Search" asp-controller="Category">View Category </a></li>
                         <li><a asp-action="Add" asp-controller="Users">Add Users </a></li>
                        <li><a asp-action="Add" asp-controller="Vendor">Add Vendors </a></li>
                        <li><a asp-action="Add" asp-controller="Recipe">Add Recipe for Website </a></li>
                    }
                
            


      </ul>
    </aside>

    <main>
      <nav class="navbar">
         
        <i  class="fa-solid fa-bars menu-icn" id="menu-bars" onclick="openMenu()"></i>

       
    @*    <input type="text" placeholder="Search..." />*@
  @*      <i class="fa-solid fa-bell nav-icn"></i>
        <i class="fa-solid fa-envelope nav-icn"></i>*@
            @if (_SignInManager.IsSignedIn(User)   )
            {
                <a asp-action="Details" asp-controller="Vendor" asp-route-id="@userId">
                    <img src="~/Content//Images/pic.png" id="restaurant-pic" alt="restaurant-pic" />
                </a> 
            }
            else
            {
                <a asp-action="SignUp" asp-controller="Users">
                    <img src="~/Content//Images/pic.png" id="restaurant-pic" alt="restaurant-pic" />
                </a>  
            }
        @if(_SignInManager.IsSignedIn(User))
        {
            <div>
         <span id="restaurant-name">@User.Identity.Name </span>|
        <span><a asp-action="SignOut" asp-controller="Users" style="text-decoration:none; color: #143444; font-size:20px;" >Log out</a></span> 

        </div>
        }
        
      </nav>

        <section class="mycon">
            @RenderBody()
        </section>
      </main>

      <script>
          const sideMenu = document.getElementById("side");
    const menuBtn = document.querySelector("#menu-bars");
    const closeBtn = document.getElementById("close-btn");

    function openMenu() {
        menuBtn.style.display = 'none'
        sideMenu.style.display = 'block'
        closeBtn.style.display = 'block'
    }


    function closeMenu() {
        sideMenu.style.display = 'none'
        closeBtn.style.display = 'none'
        menuBtn.style.display = 'block'
    }

          </script>
      <script src="~/Content/JS/vendor.js"></script>
     
      <script src="~/Content/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>

  </body>
</html>